import Foundation

/// The Japanese interface strings.
///
/// English is the key: each entry maps the exact English text used at the call site to its
/// Japanese equivalent. A missing entry simply renders in English, so the app is never
/// broken by an incomplete table.
///
/// Translator's notes:
/// - Japanese does not pluralise, so `%@ sources` and `%@ source` collapse to one form.
/// - `。` and `、` take no preceding space.
/// - Sentences ending in `…` keep the ellipsis, matching platform convention.
/// - `SourceDesk`, provider names and file extensions are left in Latin script.
enum JapaneseStrings {

    static let table: [String: String] = [

        // MARK: Application and menus
        "About SourceDesk": "SourceDesk について",
        "About": "情報",
        "SourceDesk Help": "SourceDesk ヘルプ",
        "SourceDesk Help…": "SourceDesk ヘルプ…",
        "SourceDesk on GitHub": "GitHub の SourceDesk",
        "Settings…": "設定…",
        "Settings": "設定",
        "Quit SourceDesk": "SourceDesk を終了",
        "Help": "ヘルプ",
        "License": "ライセンス",
        "Dependencies": "依存関係",
        "Diagnostics": "診断",
        "Storage": "保存場所",
        "Performance": "パフォーマンス",
        "Advanced": "詳細",
        "Credentials": "認証情報",

        // MARK: Sections
        "Research": "リサーチ",
        "Sources": "ソース",
        "Notes": "ノート",
        "Study Tools": "学習ツール",
        "Search": "検索",
        "Inspector": "インスペクタ",

        // MARK: Common actions
        "Add": "追加",
        "Add API Key…": "API キーを追加…",
        "Add Files…": "ファイルを追加…",
        "Add Website": "ウェブサイトを追加",
        "Add Website…": "ウェブサイトを追加…",
        "Add Sources…": "ソースを追加…",
        "Add Text": "テキストを追加",
        "Add as Source": "ソースとして追加",
        "Paste Text…": "テキストを貼り付け…",
        "Paste text": "テキストを貼り付け",
        "Find Sources by Topic…": "トピックからソースを探す…",
        "Find Sources": "ソースを探す",
        "Find sources by topic": "トピックからソースを探す",
        "New Notebook": "新規ノートブック",
        "New Note": "新規ノート",
        "New Session": "新規セッション",
        "Save": "保存",
        "Save Note": "ノートを保存",
        "Save Key": "キーを保存",
        "Save to Notes": "ノートに保存",
        "Cancel": "キャンセル",
        "Close": "閉じる",
        "Delete": "削除",
        "Remove": "取り除く",
        "Remove Key": "キーを削除",
        "Rename…": "名前を変更…",
        "Rename Session…": "セッション名を変更…",
        "Duplicate": "複製",
        "Copy": "コピー",
        "Copy Note": "ノートをコピー",
        "Copy excerpt": "抜粋をコピー",
        "Copy the answer": "回答をコピー",
        "Retry": "再試行",
        "Show": "表示",
        "Hide": "隠す",
        "Done": "完了",
        "Next": "次へ",
        "Back": "戻る",
        "Previous": "前へ",
        "Continue": "次へ",
        "Skip": "スキップ",
        "Import…": "読み込む…",
        "Import": "読み込む",
        "Export…": "書き出す…",
        "Refresh": "更新",
        "Reset": "リセット",
        "Reset All Settings to Defaults": "すべての設定を初期値に戻す",
        "Edit": "編集",
        "Filter": "絞り込み",
        "Sort": "並べ替え",
        "Keep": "保持",
        "Mode": "モード",
        "Options": "オプション",
        "Details": "詳細",
        "Generated": "生成日",
        "Material": "素材",
        "Tools": "ツール",
        "Problem": "問題",
        "Title": "タイトル",
        "Provider": "プロバイダ",
        "Model": "モデル",
        "Models": "モデル",
        "Generate": "生成",
        "Stop": "停止",
        "Ask": "質問する",
        "Check again": "再確認",
        "Check Again": "再確認",
        "Show Default": "初期値を表示",
        "Dismiss": "閉じる",
        "Open It": "開く",
        "Theme": "テーマ",
        "Layout": "レイアウト",

        // MARK: Sidebar
        "Favorites": "お気に入り",
        "All Notebooks": "すべてのノートブック",
        "Recent": "最近",
        "Notebooks": "ノートブック",
        "Filter notebooks": "ノートブックを絞り込む",
        "No notebooks yet": "ノートブックはまだありません",
        "Notebook name": "ノートブック名",

        // MARK: Research
        "Ask a question about your sources": "ソースについて質問する",
        "Ask anything about your sources…": "ソースについて何でも質問してください…",
        "Question": "質問",
        "Answer": "回答",
        "Citations": "引用",
        "Sources used": "使用したソース",
        "No citations yet": "引用はまだありません",
        "Citations in this answer": "この回答の引用",
        "This session": "このセッション",
        "Delete This Session": "このセッションを削除",
        "Model reasoning": "モデルの推論",
        "Notebook only": "ノートブックのみ",
        "Notebook + web": "ノートブック + ウェブ",
        "Web only": "ウェブのみ",
        "Default answer scope": "既定の回答範囲",
        "Generation": "生成",
        "System prompt": "システムプロンプト",
        "Preview of the default instructions": "既定の指示のプレビュー",
        "Regenerate": "再生成",

        // MARK: Sources
        "No sources in this notebook": "このノートブックにはソースがありません",
        "All sources": "すべてのソース",
        "Select All": "すべて選択",
        "Select None": "選択を解除",
        "Add Sources": "ソースを追加",
        "Search sources": "ソースを検索",
        "Search Again": "再検索",
        "Results to keep": "保持する件数",
        "Sources to add": "追加するソース",
        "Ready": "準備完了",
        "Failed": "失敗",
        "Processing": "処理中",
        "Reading": "読み込み中",
        "Word count": "語数",
        "Passages": "抜粋",
        "Pages": "ページ",
        "Words": "語",
        "Extracted by": "抽出方法",
        "Contents": "内容",
        "Timeline": "履歴",
        "Added": "追加日",
        "Updated": "更新日",
        "Fetched": "取得日",
        "Published": "公開日",
        "Privacy": "プライバシー",
        "Extracted text": "抽出したテキスト",
        "Show how this source is split": "このソースの分割を表示",
        "Passages sent to the model": "モデルに送信される抜粋",
        "Your note on this source": "このソースへのノート",
        "Open in browser": "ブラウザで開く",
        "Open in Browser": "ブラウザで開く",
        "Open source": "ソースを開く",
        "Re-download this page": "このページを再取得",
        "Remove source": "ソースを削除",
        "Delete Source": "ソースを削除",
        "Remove All Sources…": "すべてのソースを削除…",
        "Reveal Original": "元ファイルを表示",
        "Reveal Original File": "元ファイルを表示",
        "Reveal Stored Text": "保存テキストを表示",
        "Reveal in Finder": "Finder に表示",
        "Reveal Log Folder": "ログフォルダを表示",
        "Retrieval": "検索",
        "Answer source": "回答の出典",
        "Structured content": "構造化コンテンツ",
        "Built from": "生成元",
        "Refresh from the web": "ウェブから再取得",
        "Re-index (re-chunk and re-embed)": "再索引（再分割と再埋め込み）",
        "Re-Index Every Source in This Notebook": "このノートブックの全ソースを再索引",
        "Re-index All Sources in This Notebook": "このノートブックの全ソースを再索引",
        "Replaces SourceDesk's own grounding instructions. Leave empty for the default, which requires answers to cite retrieved material and to say when it cannot.":
            "SourceDesk 自身の根拠づけ指示を置き換えます。空欄のままにすると既定の指示が使われ、回答には取得した資料の引用が求められ、引用できない場合はその旨を述べます。",

        // MARK: Notes
        "All notes": "すべてのノート",
        "Open in Notes": "ノートで開く",
        "Export Note as Markdown…": "ノートを Markdown で書き出す…",
        "Export as Markdown…": "Markdown で書き出す…",
        "This note is empty.": "このノートは空です。",
        "No note selected": "ノートが選択されていません",

        // MARK: Study tools
        "Flashcards": "単語カード",
        "Quiz": "クイズ",

        // MARK: Status and errors
        "Online": "オンライン",
        "Offline": "オフライン",
        "No sources yet": "ソースがまだありません",
        "Nothing found": "見つかりませんでした",
        "No matches": "一致するものがありません",
        "Loading…": "読み込み中…",
        "Looking for models…": "モデルを探しています…",
        "Searching…": "検索中…",
        "Thinking…": "考えています…",
        "Preparing material from your sources…": "ソースから素材を準備しています…",
        "Restoring sources, passages, conversations and notes…":
            "ソース、抜粋、会話、ノートを復元しています…",
        "Not restored": "復元されませんでした",
        "Clear the search": "検索を消去",
        "Clear the filter": "絞り込みを消去",

        // MARK: Privacy
        "Local-Only Mode": "ローカルのみモード",
        "Local-only mode": "ローカルのみモード",
        "Never send source content to a cloud provider": "ソースの内容をクラウドに送信しない",
        "Ask before sending source content to a cloud provider":
            "ソースの内容をクラウドに送信する前に確認する",
        "Nothing leaves this Mac": "この Mac から何も送信されません",
        "What leaves this Mac": "この Mac から送信されるもの",
        "Cloud access approved for this notebook": "このノートブックのクラウド利用を許可済み",
        "Notebooks approved for cloud use": "クラウド利用を許可したノートブック",
        "Approve for this notebook": "このノートブックで許可",
        "Approval applies to this notebook only.": "許可はこのノートブックにのみ適用されます。",
        "Approval is granted per notebook, so one click cannot expose an entire library.":
            "許可はノートブックごとに与えられるため、1 回の操作でライブラリ全体が公開されることはありません。",
        "You can revoke it at any time in Settings → Privacy.":
            "設定 → プライバシー からいつでも取り消せます。",
        "Revoke": "取り消す",
        "Cloud confirmation": "クラウドの確認",
        "This is a cloud provider. When you ask a question, the passages it uses are sent to that provider so it can answer. SourceDesk asks for confirmation the first time you do this for each notebook.":
            "これはクラウドプロバイダです。質問すると、使用する抜粋が回答のためにそのプロバイダへ送信されます。SourceDesk はノートブックごとに最初の 1 回だけ確認します。",
        "To answer from your sources, SourceDesk sends the passages it retrieved — not your whole library — to the selected provider. Your notebook, files and database stay on this Mac.":
            "ソースから回答するため、SourceDesk は取得した抜粋のみ（ライブラリ全体ではありません）を選択したプロバイダへ送信します。ノートブック、ファイル、データベースはこの Mac に残ります。",
        "Local-Only Mode is on: cloud providers are disabled.":
            "ローカルのみモードが有効です。クラウドプロバイダは利用できません。",
        "While this is on, cloud providers are unavailable and SourceDesk says so rather than quietly falling back. Local models, local search and every study tool keep working.":
            "これが有効な間、クラウドプロバイダは利用できず、SourceDesk は黙って代替せずその旨を伝えます。ローカルモデル、ローカル検索、すべての学習ツールは引き続き動作します。",
        "Use a local model instead": "代わりにローカルモデルを使う",
        "Offline: answers use your saved sources and (if selected) a local model.":
            "オフライン: 保存済みのソースと（選択していれば）ローカルモデルで回答します。",
        "Offline: your sources, questions, notes and local models.":
            "オフライン: ソース、質問、ノート、ローカルモデル。",
        "Online: web search, downloading pages, and any cloud model you connect.":
            "オンライン: ウェブ検索、ページの取得、接続したクラウドモデル。",
        "Searches the web with your configured search provider. Nothing is sent to an AI provider until you ask a question.":
            "設定した検索プロバイダでウェブを検索します。質問するまで AI プロバイダには何も送信されません。",
        "Searching uses DuckDuckGo, which needs no key.":
            "検索には DuckDuckGo を使用します。キーは不要です。",
        "DuckDuckGo finds candidates and your selected AI model chooses the useful ones. Nothing is downloaded until you approve it.":
            "DuckDuckGo が候補を探し、選択した AI モデルが有用なものを選びます。承認するまで何もダウンロードされません。",
        "Nothing is downloaded until you approve a result.":
            "結果を承認するまで何もダウンロードされません。",
        "Your topic and the search result titles are sent to the selected model so it can choose between them.":
            "あなたのトピックと検索結果のタイトルが、選択のため選択中のモデルへ送信されます。",
        "The page is fetched once, now, and stored locally.":
            "ページは今 1 回だけ取得され、ローカルに保存されます。",
        "Sign-in and paywalled pages cannot be read — save those as a PDF and import the file.":
            "ログインが必要なページや有料ページは読み取れません。PDF として保存し、そのファイルを読み込んでください。",
        "On by default. SourceDesk never attempts to bypass a sign-in, a paywall or an access control — it reports the problem and suggests importing the content another way.":
            "既定で有効です。SourceDesk はログイン、有料壁、アクセス制御を回避しようとは決してしません。問題を報告し、別の方法で内容を読み込むよう提案します。",
        "Respect robots.txt when downloading pages": "ページ取得時に robots.txt を尊重する",
        "robots.txt is respected; a site that refuses automated access is reported, not bypassed.":
            "robots.txt を尊重します。自動アクセスを拒否するサイトは回避せず、その旨を報告します。",
        "Fetch full page text for search results": "検索結果の全文を取得",
        "When on, SourceDesk reads the top results so answers use real page text rather than a snippet. robots.txt is respected.":
            "有効にすると、上位の結果を読み込み、抜粋ではなく実際のページ本文を使って回答します。robots.txt は尊重されます。",
        "Web fetching": "ウェブ取得",

        // MARK: Settings
        "Language": "言語",
        "Interface Language": "表示言語",
        "System": "システム",
        "English": "English",
        "Japanese": "日本語",
        "Changes apply immediately.": "変更はすぐに反映されます。",

        // MARK: Onboarding
        "A research notebook that keeps your sources on your Mac.":
            "ソースを Mac に保管するリサーチノートブック。",
        "A notebook groups sources with the questions and notes about them.":
            "ノートブックは、ソースとその質問・ノートをまとめます。",
        "A few things worth knowing:": "知っておくと役立つこと:",
        "Create my first notebook now": "最初のノートブックを作成",
        "SourceDesk can use a model on this Mac, or a cloud provider you connect.":
            "SourceDesk はこの Mac 上のモデル、または接続したクラウドプロバイダを利用できます。",
        "Ollama runs models on this Mac, so questions and sources stay on it. It needs at least one model pulled, and enough memory for the model you pick.":
            "Ollama はこの Mac 上でモデルを実行するため、質問もソースも Mac から出ません。少なくとも 1 つのモデルの取得と、選んだモデルに見合うメモリが必要です。",
        "Choose a model": "モデルを選択",
        "Use This Provider": "このプロバイダを使う",
        "Self-hosted or compatible providers": "セルフホストまたは互換プロバイダ",
        "Ways to add a source once you are in:": "ソースの追加方法:",
        "Everything you paste is stored on this Mac and treated as a source with the same citations as any other.":
            "貼り付けた内容はこの Mac に保存され、他のソースと同じ引用を持つソースとして扱われます。",
        "Notes, an article, a transcript…": "メモ、記事、文字起こし…",
        "Optional focus, e.g. “causes of the delay”": "任意の焦点（例: 「遅延の原因」）",
        "Topic, e.g. “causes of the industrial decline”": "トピック（例: 「産業衰退の原因」）",

        // MARK: Import and export
        "Export notebook": "ノートブックを書き出す",
        "Export Notebook…": "ノートブックを書き出す…",
        "Import notebook": "ノートブックを読み込む",
        "Import Notebook…": "ノートブックを読み込む…",
        "Import Folder…": "フォルダを読み込む…",
        "Choose Location and Export…": "保存先を選んで書き出す…",
        "Choose a .nbk Archive…": ".nbk アーカイブを選択…",
        "Exports to an open, documented archive: a plain zip you can open with any tool. API keys and application settings are never included.":
            "オープンで文書化されたアーカイブとして書き出します。任意のツールで開ける単純な zip です。API キーとアプリ設定は含まれません。",
        "Importing always creates a new notebook with its own identity, so importing twice never overwrites existing work.":
            "読み込みは常に固有の新しいノートブックを作成するため、二度読み込んでも既存の作業が上書きされることはありません。",
        "Include original downloaded files": "元のダウンロードファイルを含める",
        "Include stored vectors (skips re-embedding on import)": "保存済みベクトルを含める（読み込み時の再埋め込みを省略）",
        "Include readable Markdown copies of chats and notes": "会話とノートの Markdown コピーを含める",
        "Archive layout": "アーカイブの構成",
        "Archive contents": "アーカイブの内容",
        "Keep a copy of original downloaded files": "元のダウンロードファイルのコピーを保持",
        "Keeping the original means a source survives the file being moved or deleted, and can be re-extracted without re-downloading.":
            "元ファイルを保持すると、ファイルが移動・削除されてもソースは残り、再ダウンロードせずに再抽出できます。",

        // MARK: Retrieval and performance settings
        "Search methods": "検索方法",
        "Semantic search (embeddings)": "セマンティック検索（埋め込み）",
        "Keyword search (full-text index)": "キーワード検索（全文インデックス）",
        "Embeddings": "埋め込み",
        "Ranking": "ランキング",
        "Chunking": "分割",
        "Prefix passages with their heading": "抜粋に見出しを付与",
        "Hybrid retrieval runs both and merges the rankings, so losing one method degrades recall rather than breaking search.":
            "ハイブリッド検索は両方を実行して順位を統合するため、片方が使えなくても検索が壊れず、再現率が下がるだけです。",
        "Changing the embedding model, chunk size or overlap requires re-indexing for the new settings to take effect. Sources keep working either way.":
            "埋め込みモデル、分割サイズ、重複を変更した場合、新しい設定を反映するには再索引が必要です。どちらの場合もソースは動作し続けます。",

        // MARK: Data and maintenance
        "Cache": "キャッシュ",
        "Clear Cache": "キャッシュを消去",
        "Database": "データベース",
        "Run Integrity Check": "整合性チェックを実行",
        "Optimise Database": "データベースを最適化",
        "Limits": "上限",
        "Location": "保存場所",
        "Show the inspector panel": "インスペクタパネルを表示",
        "Show word and passage counts in the source list": "ソース一覧に語数と抜粋数を表示",
        "The inspector shows the selected source, the citations behind the current answer, and note provenance.":
            "インスペクタには、選択したソース、現在の回答の根拠となる引用、ノートの出所が表示されます。",
        "Downloaded pages and intermediate files are cached so imports are not repeated. Clearing the cache never touches sources, notes or conversations.":
            "取得したページと中間ファイルはキャッシュされ、読み込みが繰り返されません。キャッシュを消去してもソース、ノート、会話は影響を受けません。",
        "Logs stay on this Mac in": "ログはこの Mac の次の場所に保存されます:",
        "Your library lives at": "ライブラリの場所:",
        "To move your library, quit SourceDesk, move the folder, then set the new path here and relaunch.":
            "ライブラリを移動するには、SourceDesk を終了してフォルダを移動し、ここで新しいパスを設定して再起動します。",
        "Resetting settings never touches notebooks, sources, notes or conversations.":
            "設定をリセットしてもノートブック、ソース、ノート、会話は影響を受けません。",
        "The extracted text, stored files and passages for every source in this notebook will be deleted from this Mac. The notebook, its chats and its notes stay.":
            "このノートブックの全ソースについて、抽出テキスト、保存ファイル、抜粋がこの Mac から削除されます。ノートブック、その会話とノートは残ります。",
        "Show Recent Log": "最近のログを表示",
        "Refresh Model Lists": "モデル一覧を更新",
        "Refresh Models": "モデルを更新",
        "Test Connection": "接続をテスト",

        // MARK: Grounding and about
        "How answers stay grounded": "回答の根拠を保つ仕組み",
        "No third-party packages. SourceDesk uses only Apple frameworks — SwiftUI, AppKit, PDFKit, Network — plus SQLite and zlib, which ship with macOS.":
            "サードパーティ製パッケージはありません。SourceDesk は Apple のフレームワーク（SwiftUI、AppKit、PDFKit、Network）と、macOS に同梱される SQLite および zlib のみを使用します。",
        "MIT. SourceDesk is an independent project; it is not affiliated with, and contains no assets or code from, Google NotebookLM or any other product.":
            "MIT。SourceDesk は独立したプロジェクトであり、Google NotebookLM その他の製品と提携しておらず、それらの資産やコードを含みません。",
        "API keys are stored in the macOS Keychain, scoped to this app. They are never written to the notebook database, a settings file, a log, or an exported notebook. Removing a key here deletes it from the Keychain.":
            "API キーはこのアプリ専用として macOS キーチェーンに保存されます。ノートブックのデータベース、設定ファイル、ログ、書き出したノートブックには決して書き込まれません。ここでキーを削除するとキーチェーンからも削除されます。",
        "Keys are stored in the macOS Keychain, never in a notebook, a settings file or an export.":
            "キーは macOS キーチェーンに保存され、ノートブック、設定ファイル、書き出しファイルには入りません。",
    
        // MARK: Strings containing values
        //
        // English is written with %@ where a value goes, so the translator can move it —
        // Japanese puts counters and particles in a different order from English. The
        // call site passes the values positionally: L("%@ of %@ results", a, b).
        "%@ of %@ tokens": "%@ / %@ トークン",
        "Untitled notebook": "無題のノートブック",
        "%@ tokens": "%@ トークン",
        "%@ tokens out": "出力 %@ トークン",
        "%@ tokens in": "入力 %@ トークン",
        "%@ sources": "%@ 件のソース",
        "%@ source": "%@ 件のソース",
        "%@ passages": "%@ 件の抜粋",
        "%@ words": "%@ 語",
        "%@ pages": "%@ ページ",
        "%@ candidates": "%@ 件の候補",
        "%@ per source": "ソースあたり %@",
        "%@ pt": "%@ pt",
        "%@ s": "%@ 秒",
        "%@ results": "%@ 件の結果",
        "%@ selected": "%@ 件を選択",
        "Add %@ Selected": "%@ 件を追加",
        "Add %@ Sources": "%@ 件のソースを追加",
        "Add %@ Source": "%@ 件のソースを追加",
        "All sources (%@)": "すべてのソース（%@）",
        "Downloading %@ of %@": "%@ / %@ をダウンロード中",
        "Searched for “%@”": "「%@」を検索しました",
        "The model chose %@ of %@ results.": "モデルは %@ 件の結果から %@ 件を選びました。",
        "The model chose these %@ from %@ results.": "モデルは %@ 件の結果からこれら %@ 件を選びました。",
        "Showing the first %@ of %@ passages.": "最初の %@ 件を表示しています（全 %@ 件）。",
        "Remove all %@": "すべての%@を削除",
        "This notebook has %@": "このノートブックには%@があります",
        "Include %@": "%@を含める",
        "Add %@…": "%@を追加…",
        "Step %@ of %@": "%@ / %@ ステップ",
        "Your library lives at %@.": "ライブラリの場所: %@",
        "Logs stay on this Mac in %@. Nothing is transmitted anywhere.":
            "ログはこの Mac の %@ に保存されます。どこにも送信されません。",
        "Exported %@": "%@ を書き出しました",
        "Imported “%@”": "「%@」を読み込みました",
        "Send source content to %@": "ソースの内容を %@ へ送信",
        "Your topic and the search result titles are sent to %@ so it can choose between them.":
            "あなたのトピックと検索結果のタイトルは、選択のため %@ へ送信されます。",
        "Use %@": "%@ を使用",
        "Embedding models: %@": "埋め込みモデル: %@",
        "queries go to %@": "検索先: %@",
        "AI Provider Settings…": "AI プロバイダ設定…",
        "AI Providers": "AI プロバイダ",
        "Add a website": "ウェブサイトを追加",
        "Already in this notebook — re-adding refreshes the stored copy.": "このノートブックに既にあります。再度追加すると保存済みのコピーが更新されます。",
        "Appearance": "外観",
        "Ask a question and the passages behind the answer appear here — with their source, page and excerpt, so you can check the answer rather than trust it.": "質問すると、回答の根拠となる抜粋がここに表示されます。出典、ページ、引用が示されるので、回答を鵜呑みにせず確認できます。",
        "Behaviour": "動作",
        "Command palette": "コマンドパレット",
        "Local server": "ローカルサーバ",
        "Nothing was selected. Try different wording.": "何も選択されませんでした。別の言い方を試してください。",
        "Research & Write a Note…": "リサーチしてノートを書く…",
        "Research a Topic (auto-add)…": "トピックをリサーチ（自動追加）…",
        "Search provider": "検索プロバイダ",
        "Select a note to see where it came from, or generate study material from the Study Tools section.": "ノートを選ぶと出所が表示されます。学習ツールのセクションから学習素材を生成することもできます。",
        "Select a notebook first.": "先にノートブックを選択してください。",
        "Show Command Palette…": "コマンドパレットを表示…",
        "Start Research": "リサーチを開始",
        "The original file is kept in the same folder, so the source survives the file being moved.": "元のファイルは同じフォルダに保持されるため、ファイルが移動してもソースは残ります。",
        "This source has no passages yet — re-index it from the actions above.": "このソースにはまだ抜粋がありません。上の操作から再索引してください。",
        "Try a notebook name, a source title, or a command like “export”.": "ノートブック名、ソースのタイトル、または「export」のようなコマンドを試してください。",
        "the AI picks this many from the search results": "AI が検索結果から選ぶ件数",
        "%@ of %@ results": "%@ / %@ 件の結果",
        "Add %@ files": "%@ 件のファイルを追加",
        "A chronological list drawn from dates in the material.": "資料に現れる日付から作る時系列の一覧。",
        "A hierarchical outline following the material's own structure.": "資料そのものの構成に沿った階層的なアウトライン。",
        "Add your first source": "最初のソースを追加",
        "All": "すべて",
        "An overview, the main points, and what the material leaves unsettled.": "全体像、要点、そして資料が結論を出していない点。",
        "Answer detail": "回答の詳細",
        "Answers ignore this notebook and use live web results only.": "このノートブックは使わず、ウェブの結果のみで回答します。",
        "Answers use only the sources in this notebook. Nothing is sent anywhere except your selected model.": "このノートブックのソースのみで回答します。選択したモデル以外には何も送信されません。",
        "Answers use this notebook's sources plus live web results. Web results are labelled separately and every query is sent to your search provider.": "このノートブックのソースとウェブの結果を併用します。ウェブの結果は別ものとして表示され、検索のたびにクエリが検索プロバイダに送信されます。",
        "Ask about your sources…": "ソースについて質問…",
        "Ask using your sources and the web…": "ソースとウェブを使って質問…",
        "Asking the model which results are relevant…": "どの結果が関連するかモデルに問い合わせています…",
        "Asks the selected local chat model to rank candidates. Slowest, best precision. Falls back to lexical if the model is offline.": "選択中のローカルモデルに候補の順位付けを依頼します。最も低速ですが精度は最高です。モデルが使えない場合は語彙ベースに戻ります。",
        "Briefing": "ブリーフィング",
        "Built-in (hashing)": "内蔵（ハッシュ方式）",
        "Cancelled": "中止",
        "Concepts, how they connect, and questions to test yourself.": "概念、そのつながり、そして自分を試すための問い。",
        "Cross-encoder (local model)": "クロスエンコーダ（ローカルモデル）",
        "Dark": "ダーク",
        "Date added": "追加日",
        "Deterministic 384-dimension lexical vectors computed on this Mac. No model download, instant, and never leaves the machine.": "この Mac で計算する決定的な 384 次元の語彙ベクトル。モデルのダウンロード不要で即時、しかも Mac から出ません。",
        "Downloading": "ダウンロード中",
        "EPUB": "EPUB",
        "Eight to twelve specific, checkable points, ordered by importance.": "重要度順に並べた、確認可能な具体的な要点を 8〜12 項目。",
        "Embedding": "埋め込み中",
        "Enter a topic. SourceDesk searches the web, adds the top results as sources, then writes a summary note from them.": "トピックを入力してください。ウェブを検索し、上位の結果をソースとして追加したうえで、それらから要約ノートを作成します。",
        "Enter a topic. SourceDesk searches the web, then downloads and indexes the top results as sources you can cite.": "トピックを入力してください。ウェブを検索し、上位の結果をダウンロードして索引化し、引用できるソースにします。",
        "Excluded": "除外",
        "Extracting": "抽出中",
        "FAQ": "FAQ",
        "Folder": "フォルダ",
        "Free-form notes from the selected material.": "選択した資料からの自由記述のノート。",
        "Get started": "はじめる",
        "HTML": "HTML",
        "Key Points": "要点",
        "Lexical (built-in)": "語彙ベース（内蔵）",
        "Light": "ライト",
        "Local model (Ollama)": "ローカルモデル（Ollama）",
        "Local: your sources stay on this Mac.": "ローカル: ソースはこの Mac に残ります。",
        "Markdown": "Markdown",
        "Multiple-choice questions with answers, explanations and scoring.": "選択式の問題と、解答・解説・採点。",
        "Needs attention": "要確認",
        "No AI model is selected. Choose one in the toolbar.": "AI モデルが選択されていません。ツールバーで選んでください。",
        "No provider selected": "プロバイダが選択されていません",
        "Not checked yet": "まだ確認していません",
        "Note": "ノート",
        "Notebook + Web": "ノートブック + ウェブ",
        "Off": "オフ",
        "Off (keyword search only)": "オフ（キーワード検索のみ）",
        "Only keyword and metadata search run. Answers still work; recall is narrower.": "キーワードとメタデータの検索のみを行います。回答は可能ですが、再現率は下がります。",
        "Open SourceDesk": "SourceDesk を開く",
        "Outline": "アウトライン",
        "PDF": "PDF",
        "Partial": "一部完了",
        "Pasted Text": "貼り付けたテキスト",
        "Question-and-answer cards you can step through here.": "その場でめくれる一問一答のカード。",
        "Questions a careful reader would ask, with direct answers.": "注意深い読み手なら抱く疑問と、その直接の答え。",
        "Queued": "待機中",
        "Quotations": "引用集",
        "Re-scores the top candidates using term coverage and phrase proximity. No model needed.": "語の網羅率と言葉の近さで上位候補を採点し直します。モデルは不要です。",
        "Research & Add Sources": "リサーチしてソースを追加",
        "Research & Create Note": "リサーチしてノートを作成",
        "Rich Text": "リッチテキスト",
        "Runs Ollama's hosted models on ollama.com": "ollama.com のホスト版モデルを実行します",
        "Search is switched off. Choose a search provider in Settings → Search.": "検索が無効です。設定 → 検索 で検索プロバイダを選んでください。",
        "Search the web…": "ウェブを検索…",
        "Searching DuckDuckGo…": "DuckDuckGo で検索中…",
        "Sent to your AI provider": "AI プロバイダに送信されます",
        "Sent to your search provider": "検索プロバイダに送信されます",
        "Size": "サイズ",
        "Source": "ソース",
        "Source Comparison": "ソース比較",
        "Sources + Web": "ソース + ウェブ",
        "Stays on this Mac": "この Mac に残ります",
        "Study Guide": "学習ガイド",
        "Study material": "学習素材",
        "Summary": "要約",
        "Text": "テキスト",
        "The important points, context, and what remains uncertain.": "重要な点、その背景、そして未確定な部分。",
        "This marker did not resolve to a retrieved passage.": "この印は取得した抜粋に結び付きませんでした。",
        "This query is sent to the selected search provider.": "このクエリは選択した検索プロバイダに送信されます。",
        "This source content may be sent to the selected AI provider.": "このソースの内容は選択した AI プロバイダに送信される場合があります。",
        "Use fused retrieval order as-is. Fastest.": "統合した検索順位をそのまま使います。最も高速です。",
        "Uses an embedding model served by your local Ollama install, for example nomic-embed-text. Better semantic recall, needs the model pulled once.": "ローカルの Ollama が提供する埋め込みモデル（例: nomic-embed-text）を使います。セマンティックな再現率が上がりますが、事前に 1 度モデルを取得する必要があります。",
        "Verbatim excerpts, with why each matters.": "原文どおりの抜粋と、それぞれが重要な理由。",
        "Web": "ウェブ",
        "Web: this query is sent to your search provider.": "ウェブ: このクエリは検索プロバイダに送信されます。",
        "Website": "ウェブサイト",
        "Welcome to SourceDesk": "SourceDesk へようこそ",
        "Where two or more sources agree, disagree, and what each adds.": "2 つ以上のソースが一致する点、対立する点、それぞれが付け加える点。",
        "Word": "Word",
        "You are ready": "準備ができました",
        "Your source stays on this Mac.": "ソースはこの Mac に残ります。",
        "%@ passage": "%@ 件の抜粋",
        "%@ word": "%@ 語",
        "%@ page": "%@ ページ",
        "%@ note": "%@ 件のノート",
        "%@ notes": "%@ 件のノート",
        "%@ message": "%@ 件のメッセージ",
        "%@ messages": "%@ 件のメッセージ",
        "%@ result": "%@ 件の結果",
        "%@ file": "%@ 件のファイル",
        "%@ files": "%@ 件のファイル",
        "%@ item": "%@ 項目",
        "%@ items": "%@ 項目",
        "%@ chunk": "%@ 件の抜粋",
        "%@ chunks": "%@ 件の抜粋",
        "%@ citation": "%@ 件の引用",
        "%@ citations": "%@ 件の引用",
        "%@ session": "%@ 件のセッション",
        "%@ sessions": "%@ 件のセッション",
        "%@ token": "%@ トークン",
        "%@ candidate": "%@ 件の候補",
        "%@ day": "%@ 日前",
        "%@ days": "%@ 日前",
        "%@ could not be added.": "%@ を追加できませんでした。",
        "Show %@": "%@ を表示",
    ]
}
